### ISSUE TITLE
Erro no Observable

### ISSUE THREAD

**Issue by raphaelramos** [assuncaocharles/telefone-mask-ng2#1]
Após executar npm update, acontece o erro no compilador

> ERROR in .../angular/node_modules/telefone-mask-ng2/node_modules/rxjs/Subject.d.ts (16,22): Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
>   Types of property 'lift' are incompatible.
>     Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
>       Type 'Observable<T>' is not assignable to type 'Observable<R>'.
>         Type 'T' is not assignable to type 'R'.

**Comment by assuncaocharles** [comment]
Parece ser um problema de compatibilidade entre as versões de RXJS e do TS. Tenta novamente com a versão 2.4.0 do TS e veja se o erro persiste.

**Comment by joaopavila** [comment]
Pra mim também aconteceu o mesmo problema, mas isso não deveria ter que me forçar a usar uma versão mais antiga do TS.

Solta uma versão com essa correção e sucesso :)

**Comment by assuncaocharles** [comment]
@joaopavila Problema corrigido na versão 1.0.7. Funcionando como deveria :)
